version: "3"
#
networks:
  nginx_proxy:
    external:
      name: nginx_proxy
  default:
    driver: bridge
#
volumes:
  portainer_data:
#
services:
  portainer:
    image: portainer/portainer
    restart: always
    environment:
      - TZ= ${TIME_ZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - ${PORTAINER_HTTP_PORT}:9000
    networks:
      - nginx_proxy
      - default
